<?php
namespace Xin\Thrift\Account;
/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


interface AccountIf {
  /**
   * @param string $username
   * @param string $password
   * @return \Xin\Thrift\Account\LoginResponse
   */
  public function login($username, $password);
  /**
   * @param string $token
   * @return \Xin\Thrift\Account\User
   */
  public function user($token);
}


